---
- hosts: proxmox
  become: false
  gather_facts: false
  vars:
    packages:
      - 'python-pip'
    pip_packages:
      - 'proxmoxer'
    node: 'pve1'
    # api_user: 'root@pam'
    # api_passwd: ''
    api_host: '{{ ansible_host }}'
    # cts:
    #   lxccent:
    #     container_password: 'p@ssw0rd'
    #     container_template: 'local:vztmpl/centos-7-default_20171212_amd64.tar.xz'
    #     container_cpus: 2
    #     container_disk: 10
    #     container_memory: 2048
    #     container_storage: 'pve1-data3'
    #     container_net: '{"net0":"name=eth0,gw=10.88.255.254,ip=10.88.89.100/16,bridge=vmbr0"}'
    #     container_dns: '10.88.255.254'
    #     container_vmid: 89100
    #   lxcubun:
    #     container_password: 'p@ssw0rd'
    #     container_template: 'local:vztmpl/ubuntu-18.04-standard_18.04.1-1_amd64.tar.gz'
    #     container_cpus: 2
    #     container_disk: 10
    #     container_memory: 2048
    #     container_storage: 'pve1-data3'
    #     container_net: '{"net0":"name=eth0,gw=10.88.255.254,ip=10.88.89.101/16,bridge=vmbr0"}'
    #     container_dns: '10.88.255.254'
    #     container_vmid: 89101
  tasks:
    
    - name: Create new container automatically selecting the next available vmid.
      proxmox:
        node: '{{ node }}'
        api_user: '{{ api_user }}'
        api_password: '{{ api_passwd }}'
        api_host: '{{ api_host }}'
        vmid: '{{ item.value.container_vmid }}'
        password: '{{ item.value.container_password }}'
        hostname: '{{ item.key }}'
        cores: '{{ item.value.container_cpus }}'
        memory: '{{ item.value.container_memory }}'
        disk: '{{ item.value.container_disk }}'
        storage: '{{ item.value.container_storage }}'
        netif: '{{ item.value.container_net }}'
        nameserver: '{{ item.value.container_dns }}'
        searchdomain: '{{ item.value.container_dns }}'
        onboot: true
        ostemplate: '{{ item.value.container_template }}'
      with_dict: '{{ cts }}'
      notify:
        - 'sleep'
      register: 'create_cts_pve'

    - meta: 'flush_handlers'
      when: 'created_cts_pve.changed'
    # - debug: var="create_cts_pve"
    - name: start container
      proxmox:
        node: '{{ node }}'
        api_user: '{{ api_user }}'
        api_password: '{{ api_passwd }}'
        api_host: '{{ api_host }}'
        vmid: '{{ item.value.container_vmid }}'
        state: started
      with_dict: '{{ cts }}'
  
  handlers:
    - name: 'sleep'
      pause:
        seconds: 10