---
- hosts: proxmox-pve1
  become: false
  gather_facts: false
  vars:
    packages:
      - 'python-pip'
    pip_packages:
      - 'proxmoxer'
    node: 'pve1'
    api_user: 'root@pam'
    api_passwd: 'OpstaTh@1l@nd'
    api_host: '{{ ansible_host }}'
    container_hostname: 'ansible.opsta'
    container_password: 'p@ssw0rd'
    container_template: 'local:vztmpl/ubuntu-18.04-standard_18.04.1-1_amd64.tar.gz'
    container_cpus: 2
    container_disk: 10
    container_memory: 2048
    container_storage: 'pve1-data3'
    container_net: '{"net0":"name=eth0,gw=10.88.255.254,ip=10.88.89.100/16,bridge=vmbr0"}'
    container_dns: '10.88.255.254'
    container_vmid: 89100
  tasks:
    
    - name: Create new container automatically selecting the next available vmid.
      proxmox:
        node: '{{ node }}'
        api_user: '{{ api_user }}'
        api_password: '{{ api_passwd }}'
        api_host: '{{ api_host }}'
        vmid: '{{ container_vmid }}'
        password: '{{ container_password }}'
        hostname: '{{ container_hostname }}'
        cores: '{{ container_cpus }}'
        memory: '{{ container_memory }}'
        disk: '{{ container_disk }}'
        storage: '{{ container_storage }}'
        netif: '{{ container_net }}'
        nameserver: '{{ container_dns }}'
        searchdomain: '{{ container_dns }}'
        onboot: true
        ostemplate: '{{ container_template }}'
      notify:
        - 'sleep'
      register: 'create_cts_pve'

    - meta: 'flush_handlers'
      when: 'created_cts_pve.changed'
    # - debug: var="create_cts_pve"
    - name: start container
      proxmox:
        node: '{{ node }}'
        api_user: '{{ api_user }}'
        api_password: '{{ api_passwd }}'
        api_host: '{{ api_host }}'
        vmid: '{{ container_vmid }}'
        state: started
  
  handlers:
    - name: 'sleep'
      pause:
        seconds: 10