packages:
  - 'python-pip'
pip_packages:
  - 'proxmoxer'
  - 'requests'
clusters_node: 'pve2'
api_user: 'root@pam'
api_passwd: 'OpstaTh@1l@nd'
api_host: '{{ ansible_host }}'
template_name: 'rh76-cloudinit-template'
template_vmid: 200

################################################
# Example config for create VMs from templates.#
################################################
kvm:
  oc2-lb2:
    kvm_newid: 8848199
    kvm_cores: 2
    kvm_sockets: 1
    kvm_memory: 2048
    kvm_net_device: {"net0":"virtio,bridge=vmbr0,firewall=0"}
    kvm_storage: 'pve2-data4'
    kvm_state_delete: false
  vm2:
    kvm_newid: 89091
    kvm_cores: 4
    kvm_sockets: 1
    kvm_memory: 8192
    kvm_net_device: {"net0":"virtio,bridge=vmbr0,firewall=0"}
    kvm_storage: 'pve2-data3'
    kvm_state_delete: false
  vm3:
    kvm_newid: 89092
    kvm_cores: 4
    kvm_sockets: 1
    kvm_memory: 8192
    kvm_net_device: {"net0":"virtio,bridge=vmbr0,firewall=0"}
    kvm_storage: 'pve2-data2'
    kvm_state_delete: false

